---
title: "Tutoría de Matemáticas 2021"
author: "Jorge Gómez"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    fig_height: 8
    fig_width: 13
    number_section: yes
    theme: cosmo
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
    includes: \usepackage{amsmath}
---


# Suma de vectores

La suma de vectores se realiza mediante la suma de cada uno de los términos de forma individual, es decir, deben de coincidir las *X*'s con las *X*'s, así como las *Y*'s deben de asociarse unas con otras. El resultado es un vector del mismo número de dimensiones que los vectores que estamos sumando. La siguiente fórmula describe el proceso.

$$
\begin{array}{l}
\overrightarrow{V_1}=(X_1,Y_1)\\
\overrightarrow{V_2}=(X_2,Y_2)\\
\overrightarrow{V_1}+\overrightarrow{V_2}= \overrightarrow{V_3}\\
\overrightarrow{V_3}=(X_1+X_2 , Y_1+Y_2)\\
\quad \ =X_1 + X_2=X_3,\\
\quad \quad \quad  Y_1 + Y_2=Y_3\\
\overrightarrow{V_3}=(X_3 , Y_3)
\end{array}
$$
Para una más fácil realización, se deben de sustituir con los valores que se piensa trabajar, de modo que es necesario tener muy en cuenta los signos de los términos habidos dentro de los vectores. De igual modo es importante resaltar el hecho que el uso de *X*'s y de *Y*'s es meramente por cuestiones didácticas, no tiene que corresponder forzosamente a literales iguales.

# Resta de vectores

Al igual que con la suma de vectores, la resta de vectores se realiza mediante la suma de cada uno de los términos de forma individual, es decir, deben de coincidir las *X*'s con las *X*'s, así como las *Y*'s deben de asociarse unas con otras. De igual modo el resultado corresponde a un vector con el mismo número de dimensiones que aquellos que se están restando. La siguiemte fórmula describe el proceso.

$$
\begin{array}{l}
\overrightarrow{V_1}=(X_1,Y_1)\\
\overrightarrow{V_2}=(X_2,Y_2)\\
\overrightarrow{V_1}-\overrightarrow{V_2}=(X_1-X_2 ,  Y1-Y_2)\\
\end{array} 
$$
Para evitar problemas, es recomendable sustituir los valores en la fórmula para evitar complicaciones con los signos propios de los valores de los vectores; es necesario recordar que los signos que se muestra en la fórmula son propios a la fórmula, es decir, que debemos de aplicar leyes de signos en caso de ser necesario. El hecho que el uso de *X*'s y de *Y*'s es meramente por cuestiones didácticas, no tiene que corresponder forzosamente a literales iguales.

# Magnitud de vector

Para realizar esta operación, primero se deben de determinar cuáles términos van a estar dentro de la raíz cuadrada, pues se deben de resolver antes de cubrir la raíza cuadrada. De este modo queda en orden:

1. Determinar valores que irán dentro de la raíz cuadrada.
2. Resolver y simplificar los valores elevados al cuadrado. **Todo número real se vuelve positivo al elevarse al cuadrado**
3. Resolver raíz cuadrada.
4. Simplificar en caso de que se quiera/pueda/necesite.

$$
\begin{array}{l}
\overrightarrow{V_1}=(X,Y)\\
||\overrightarrow{V_1}||=\sqrt{X^2+Y^2}\\
\end{array}
$$

# Producto escalar interno

Así como en la suma y resta de vectores se realiza mediante la suma de cada uno de los términos de forma individual, es decir, deben de coincidir las *X* con las *X*, mientras que las *Y* deben de asociarse unas con otras. La formula siguiente describe el proceso.
$$
\begin{array}{l}
\overrightarrow{V_1}=(X_1,Y_1)\\
\overrightarrow{V_2}=(X_2,Y_2)\\
\overrightarrow{V_1}*\overrightarrow{V_2}=X_1*X_2+Y_1*Y_2
\end{array}
$$

Describiendo el proceso, se deben de tomar las parejas de los números y multiplicarlos, siempre recordando que las *X's* siempre van con las *X's* y las *Y's* con las *Y's*. Una vez que se multiplican, se suman. A diferencia de la suma y resta de vectores, el producto escalar interno **NO** nos arroja un vector.

# Producto vectorial

Decimos que dos vectores son ortogonales cuando son perpendiculares uno con otro, es decir que sus productos punto nos dan 0 como resultado. El modo de resolver 
